import { describe, it, expect } from 'vitest'
import { automationVerdict, isAutomated } from '../shared/bulkMail'
import { gigTerms, planReplyScan } from '../src/lib/gmailReplies'
import { matchStrength, strengthNote, type ReplyCandidate } from '../shared/replyMatch'

const TODAY = '2026-09-16'

describe('what the scan asks Gmail for', () => {
  const terms = (name: string) => gigTerms({ name })

  it('no longer asks for a bare city name', () => {
    // The measured fault: "Sofar Sounds Winnipeg" reduced to the single word
    // "winnipeg", which for somebody living in Winnipeg is most of their mail.
    const t = terms('Sofar Sounds Winnipeg — Artist Application')
    expect(t).not.toContain('winnipeg')
    expect(t.some((x) => x === 'sounds' || x === 'sofar')).toBe(false)
  })

  it('asks for two words that must both appear instead', () => {
    const t = terms('Sofar Sounds Winnipeg — Artist Application')
    const conjunction = t.find((x) => x.startsWith('('))
    expect(conjunction).toBeTruthy()
    // Gmail reads a space inside parentheses as AND.
    expect(conjunction!.split(' ').length).toBe(2)
  })

  it('still asks for the full name outright', () => {
    expect(terms('Sofar Sounds Winnipeg — Artist Application').some((x) => x.startsWith('"'))).toBe(true)
  })

  it('keeps the one-word escape hatch, which nothing else would find', () => {
    expect(terms('JIMWEEK')).toContain('jimweek')
  })

  it('searches spam with precise terms and never with loose ones', () => {
    // The old query reached spam with everything, which is how actual spam got
    // into the queue. The property worth keeping is that a rejection filed as
    // spam is still found — and a message carrying the festival's whole name
    // is worth digging out of there. A two-word conjunction is not.
    const gigs = [
      { id: 1, name: 'Sofar Sounds Winnipeg — Artist Application', status: 'submitted', submittedAt: '2026-08-01' },
    ] as Parameters<typeof planReplyScan>[0]['gigs']

    const { queries } = planReplyScan({ gigs, today: TODAY })
    const anywhere = queries.filter((q) => q.includes('in:anywhere'))
    const primary = queries.filter((q) => q.includes('category:primary'))

    expect(anywhere.length).toBeGreaterThan(0)
    expect(primary.length).toBeGreaterThan(0)
    for (const q of anywhere) expect(q).not.toMatch(/\(\w+ \w+\)/)
    for (const q of primary) expect(q).toMatch(/\(\w+ \w+\)/)
    for (const q of primary) expect(q).toContain('-in:spam')
  })
})

describe('mail that says it was not written by a person', () => {
  it('excludes a mailing list, which only list software may label', () => {
    // RFC 2919 says List-Id must only be generated by list software.
    expect(isAutomated({ 'list-id': '<news.example.com>' })).toBe(true)
  })

  it('excludes an auto-responder that announced itself', () => {
    // RFC 3834: anything but `no` is the sender saying it is automatic.
    expect(isAutomated({ 'auto-submitted': 'auto-replied' })).toBe(true)
    expect(isAutomated({ 'auto-submitted': 'auto-generated' })).toBe(true)
  })

  it('treats an explicit "no" as what it says', () => {
    expect(isAutomated({ 'auto-submitted': 'no' })).toBe(false)
  })

  it('keeps bulk mail rather than excluding it', () => {
    // The whole reason for two tiers: a festival that mails through a platform
    // is still a festival, and its acceptance letter carries these headers.
    const v = automationVerdict({ 'list-unsubscribe': '<https://x.example/u>' })
    expect(v.tier).toBe('bulk')
    expect(isAutomated({ 'list-unsubscribe': '<https://x.example/u>' })).toBe(false)
  })

  it('reads the legacy bulk marker without relying on it', () => {
    expect(automationVerdict({ precedence: 'bulk' }).tier).toBe('bulk')
    expect(automationVerdict({ precedence: 'first-class' }).tier).toBe('unremarkable')
  })

  it('says nothing about mail that carries none of these', () => {
    const v = automationVerdict({ from: 'organiser@festival.example', subject: 'Re: your application' })
    expect(v.tier).toBe('unremarkable')
    expect(v.reasons).toEqual([])
  })

  it('ignores an empty header rather than reading it as present', () => {
    expect(automationVerdict({ 'list-id': '   ' }).tier).toBe('unremarkable')
  })
})

describe('how strong a match is, said out loud', () => {
  const candidate = (over: Partial<ReplyCandidate>): ReplyCandidate =>
    ({ gigId: 1, gigName: 'A Festival', score: 26, signals: [], bound: false, ...over }) as ReplyCandidate

  it('calls one common word in a body weak, which is the case that flooded the queue', () => {
    const c = candidate({ signals: [{ id: 'name', points: 26, detail: '"winnipeg" in the body.' }], score: 26 })
    expect(matchStrength(c)).toBe('weak')
    // And says what the only evidence was, so it can be dismissed at a glance.
    expect(strengthNote('weak', c)).toContain('winnipeg')
    expect(strengthNote('weak', c)).toMatch(/only evidence/i)
  })

  it('calls a confirmed binding confirmed, whatever it scored', () => {
    expect(matchStrength(candidate({ bound: true, score: 100 }))).toBe('confirmed')
  })

  it('calls two agreeing signals likely', () => {
    const c = candidate({
      signals: [
        { id: 'name', points: 26, detail: '"voyageur" in the body.' },
        { id: 'domain', points: 30, detail: 'Sent from festival.example.' },
      ],
      score: 56,
    })
    expect(matchStrength(c)).toBe('strong')
  })

  it('calls the full name in a subject likely on its own', () => {
    const c = candidate({ signals: [{ id: 'name', points: 50, detail: '"A Festival" appears in the subject.' }], score: 50 })
    expect(matchStrength(c)).toBe('strong')
  })

  it('never calls a single weak signal anything but weak, however the score is read', () => {
    for (const points of [18, 24, 26]) {
      expect(matchStrength(candidate({ signals: [{ id: 'name', points, detail: 'x' }], score: points }))).toBe('weak')
    }
  })
})

// ── Stages 5 and 6, and the corroboration that replaced stage 4 ──────────────

import { matchReply, MATCH_THRESHOLD as BAR, type MatchableGig, type ReplyMessage } from '../shared/replyMatch'
import type { RarityIndex } from '../shared/termRarity'
import { recogniseAsks } from '../shared/replyDraft'

const RARITY: RarityIndex = { corpusSize: 12000, counts: { winnipeg: 2400, sofar: 9, sounds: 300 } }
const GIGS = [
  { id: 10, name: 'Sofar Sounds Winnipeg — Artist Application', status: 'shortlisted', url: null, organizer: null, submittedAt: '2026-08-01' },
] as unknown as MatchableGig[]

const msg = (over: Partial<ReplyMessage>): ReplyMessage =>
  ({
    messageId: 'm', threadId: 't', from: 'x@example.com', subject: 'hello',
    body: 'A note about Sofar.', receivedAt: '2026-09-16T00:00:00Z', ...over,
  }) as ReplyMessage

describe('bulk mail is weighed, never excluded', () => {
  it('sinks a lone weak lead', () => {
    const plain = matchReply(msg({}), GIGS, [], RARITY).candidates[0]
    expect(plain.score).toBeGreaterThanOrEqual(BAR)

    const bulk = matchReply(msg({ automation: 'bulk' }), GIGS, [], RARITY)
    expect(bulk.candidates).toEqual([])
  })

  it('does not touch a message that names the application outright', () => {
    // The whole reason this is a weight: a festival mailing through a platform
    // is still a festival, and its acceptance letter carries the same headers
    // a newsletter does.
    const r = matchReply(
      msg({ subject: 'Sofar Sounds Winnipeg — Artist Application', automation: 'bulk' }),
      GIGS, [], RARITY,
    )
    expect(r.candidates[0]).toBeTruthy()
    expect(r.candidates[0].score).toBeGreaterThanOrEqual(BAR)
  })

  it('never invents a candidate out of a penalty', () => {
    // Nothing pointed at this gig, so there is nothing to subtract from.
    const r = matchReply(msg({ body: 'entirely unrelated', automation: 'bulk' }), GIGS, [], RARITY)
    expect(r.candidates).toEqual([])
  })
})

describe('a thread you wrote in corroborates, and identifies nothing', () => {
  it('lifts a genuine lead and makes it read as more than one reason', () => {
    const r = matchReply(msg({ inYourThread: true }), GIGS, [], RARITY)
    expect(r.candidates[0].signals.map((s) => s.id)).toContain('replied')
    expect(r.candidates[0].signals.length).toBeGreaterThan(1)
  })

  it('puts nothing in the queue on its own', () => {
    // Being in a conversation says nothing about which application it is about.
    const r = matchReply(msg({ body: 'entirely unrelated', inYourThread: true }), GIGS, [], RARITY)
    expect(r.candidates).toEqual([])
  })

  it('rescues nothing that bulk sank, which is the right order', () => {
    const r = matchReply(msg({ inYourThread: true, automation: 'bulk' }), GIGS, [], RARITY)
    // 26 rare word + 24 thread − 20 bulk = 30, still a lead. Recorded because
    // the arithmetic is the design: bulk is a thumb on the scale, not a veto.
    expect(r.candidates[0]?.score).toBe(30)
  })
})

describe('an ask quoted back at you is not an ask', () => {
  // `recogniseAsks` has stripped the quote since it shipped; its doc comment
  // said the opposite, which is why this needed checking rather than reading.
  // Pinned here because the comment was the only record and it was wrong.
  const topPost = 'Thanks — we have everything we need.'
  const quoted = [
    'On Tue, 2 Sep 2026, Doug McArthur wrote:',
    '> Could you please send a stage plot and a press photo?',
  ].join('\n')

  it('finds the asks when the sender is the one making them', () => {
    const reading = recogniseAsks('Could you please send a stage plot and a press photo?')
    expect(reading.asks.length).toBeGreaterThan(0)
  })

  it('finds none of them under a quote marker', () => {
    const reading = recogniseAsks([topPost, '', quoted].join('\n'))
    expect(reading.asks).toEqual([])
    // And the only sentence it weighed at all was the one they wrote.
    expect(reading.unrecognised).toEqual([topPost])
  })

  it('stops at the marker, not at the angle bracket', () => {
    // Plenty of clients quote without prefixing a thing. The marker line is
    // what ends the top post, so an unprefixed quote is stripped as well.
    const reading = recogniseAsks(
      [
        topPost,
        '',
        'On Tue, 2 Sep 2026, Doug McArthur wrote:',
        'Could you please send a stage plot and a press photo?',
      ].join('\n'),
    )
    expect(reading.asks).toEqual([])
  })
})
