import { describe, it, expect } from 'vitest'
import { automationVerdict, isAutomated } from '../shared/bulkMail'
import { gigTerms, planReplyScan } from '../src/lib/gmailReplies'
import { matchStrength, strengthNote, type ReplyCandidate } from '../shared/replyMatch'

const TODAY = '2026-09-16'

describe('what the scan asks Gmail for', () => {
  const terms = (name: string) => gigTerms({ name })

  it('no longer asks for a bare city name', () => {
    // The measured fault: "Sofar Sounds Winnipeg" reduced to the single word
    // "winnipeg", which for somebody living in Winnipeg is most of their mail.
    const t = terms('Sofar Sounds Winnipeg — Artist Application')
    expect(t).not.toContain('winnipeg')
    expect(t.some((x) => x === 'sounds' || x === 'sofar')).toBe(false)
  })

  it('asks for two words that must both appear instead', () => {
    const t = terms('Sofar Sounds Winnipeg — Artist Application')
    const conjunction = t.find((x) => x.startsWith('('))
    expect(conjunction).toBeTruthy()
    // Gmail reads a space inside parentheses as AND.
    expect(conjunction!.split(' ').length).toBe(2)
  })

  it('still asks for the full name outright', () => {
    expect(terms('Sofar Sounds Winnipeg — Artist Application').some((x) => x.startsWith('"'))).toBe(true)
  })

  it('keeps the one-word escape hatch, which nothing else would find', () => {
    expect(terms('JIMWEEK')).toContain('jimweek')
  })

  it('searches spam with precise terms and never with loose ones', () => {
    // The old query reached spam with everything, which is how actual spam got
    // into the queue. The property worth keeping is that a rejection filed as
    // spam is still found — and a message carrying the festival's whole name
    // is worth digging out of there. A two-word conjunction is not.
    const gigs = [
      { id: 1, name: 'Sofar Sounds Winnipeg — Artist Application', status: 'submitted', submittedAt: '2026-08-01' },
    ] as Parameters<typeof planReplyScan>[0]['gigs']

    const { queries } = planReplyScan({ gigs, today: TODAY })
    const anywhere = queries.filter((q) => q.includes('in:anywhere'))
    const primary = queries.filter((q) => q.includes('category:primary'))

    expect(anywhere.length).toBeGreaterThan(0)
    expect(primary.length).toBeGreaterThan(0)
    for (const q of anywhere) expect(q).not.toMatch(/\(\w+ \w+\)/)
    for (const q of primary) expect(q).toMatch(/\(\w+ \w+\)/)
    for (const q of primary) expect(q).toContain('-in:spam')
  })
})

describe('mail that says it was not written by a person', () => {
  it('excludes a mailing list, which only list software may label', () => {
    // RFC 2919 says List-Id must only be generated by list software.
    expect(isAutomated({ 'list-id': '<news.example.com>' })).toBe(true)
  })

  it('excludes an auto-responder that announced itself', () => {
    // RFC 3834: anything but `no` is the sender saying it is automatic.
    expect(isAutomated({ 'auto-submitted': 'auto-replied' })).toBe(true)
    expect(isAutomated({ 'auto-submitted': 'auto-generated' })).toBe(true)
  })

  it('treats an explicit "no" as what it says', () => {
    expect(isAutomated({ 'auto-submitted': 'no' })).toBe(false)
  })

  it('keeps bulk mail rather than excluding it', () => {
    // The whole reason for two tiers: a festival that mails through a platform
    // is still a festival, and its acceptance letter carries these headers.
    const v = automationVerdict({ 'list-unsubscribe': '<https://x.example/u>' })
    expect(v.tier).toBe('bulk')
    expect(isAutomated({ 'list-unsubscribe': '<https://x.example/u>' })).toBe(false)
  })

  it('reads the legacy bulk marker without relying on it', () => {
    expect(automationVerdict({ precedence: 'bulk' }).tier).toBe('bulk')
    expect(automationVerdict({ precedence: 'first-class' }).tier).toBe('unremarkable')
  })

  it('says nothing about mail that carries none of these', () => {
    const v = automationVerdict({ from: 'organiser@festival.example', subject: 'Re: your application' })
    expect(v.tier).toBe('unremarkable')
    expect(v.reasons).toEqual([])
  })

  it('ignores an empty header rather than reading it as present', () => {
    expect(automationVerdict({ 'list-id': '   ' }).tier).toBe('unremarkable')
  })
})

describe('how strong a match is, said out loud', () => {
  const candidate = (over: Partial<ReplyCandidate>): ReplyCandidate =>
    ({ gigId: 1, gigName: 'A Festival', score: 26, signals: [], bound: false, ...over }) as ReplyCandidate

  it('calls one common word in a body weak, which is the case that flooded the queue', () => {
    const c = candidate({ signals: [{ id: 'name', points: 26, detail: '"winnipeg" in the body.' }], score: 26 })
    expect(matchStrength(c)).toBe('weak')
    // And says what the only evidence was, so it can be dismissed at a glance.
    expect(strengthNote('weak', c)).toContain('winnipeg')
    expect(strengthNote('weak', c)).toMatch(/only evidence/i)
  })

  it('calls a confirmed binding confirmed, whatever it scored', () => {
    expect(matchStrength(candidate({ bound: true, score: 100 }))).toBe('confirmed')
  })

  it('calls two agreeing signals likely', () => {
    const c = candidate({
      signals: [
        { id: 'name', points: 26, detail: '"voyageur" in the body.' },
        { id: 'domain', points: 30, detail: 'Sent from festival.example.' },
      ],
      score: 56,
    })
    expect(matchStrength(c)).toBe('strong')
  })

  it('calls the full name in a subject likely on its own', () => {
    const c = candidate({ signals: [{ id: 'name', points: 50, detail: '"A Festival" appears in the subject.' }], score: 50 })
    expect(matchStrength(c)).toBe('strong')
  })

  it('never calls a single weak signal anything but weak, however the score is read', () => {
    for (const points of [18, 24, 26]) {
      expect(matchStrength(candidate({ signals: [{ id: 'name', points, detail: 'x' }], score: points }))).toBe('weak')
    }
  })
})
