import { chromium } from 'playwright'
const DIR='/tmp/claude-0/-home-user-dougmcarthur-dashboard/27088b41-132d-5df9-a06a-e338c39af386/scratchpad'
const browser = await chromium.launch({ executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome' })
const ctx = await browser.newContext({ viewport:{ width:1280, height:1000 } })
const page = await ctx.newPage()
const cdp = await ctx.newCDPSession(page)
await cdp.send('WebAuthn.enable')
await cdp.send('WebAuthn.addVirtualAuthenticator', { options:{ protocol:'ctap2', transport:'internal', hasResidentKey:true, hasUserVerification:true, isUserVerified:true, automaticPresenceSimulation:true } })
await page.goto('http://localhost:8787/', { waitUntil:'networkidle' })
await page.getByRole('button',{name:/add a passkey/i}).click().catch(()=>{})
await page.waitForTimeout(600)
await page.locator('input').first().fill('424242')
await page.getByRole('button',{name:/add a passkey/i}).click()
await page.waitForTimeout(3000)
await page.goto('http://localhost:8787/#settings', { waitUntil:'networkidle' })
await page.waitForTimeout(2500)
const intCard = page.locator('h2:text("Integrations")').locator('xpath=../..')
console.log('EXACT "Connect" IN CARD:', await intCard.getByRole('button',{name:'Connect',exact:true}).count())
console.log('ALL BUTTON NAMES IN CARD:', JSON.stringify(
  await intCard.locator('button').evaluateAll(bs => bs.map(b => (b.getAttribute('aria-label') || b.textContent || '').trim()))))
console.log('BANNER:', (await page.locator('text=/Connecting is switched off/').count()) ? 'shown' : 'MISSING')
console.log('BANNER TEXT:', (await page.locator('p:has-text("Connecting is switched off")').first().innerText().catch(()=>'-')).replace(/\s+/g,' '))
const card = page.locator('h2:text("Integrations")').locator('xpath=../..')
await card.screenshot({ path:`${DIR}/blocked.png` })
await browser.close()
