/**
 * Whether a message says, in its own headers, that it is not a person writing
 * to you.
 *
 * The Review queue fills with newsletters, receipts and marketing because the
 * matcher only ever asked "does this text look like a gig name". Mail carries
 * a good deal of evidence about what *kind* of message it is, and some of it
 * is reliable by specification rather than by convention — which is the
 * difference between something worth excluding on and something worth
 * weighing.
 *
 * Two tiers, and the split is the whole point.
 *
 * **Automated** is close to proof. `List-Id` must only be generated by mailing
 * list software (RFC 2919), and an `Auto-Submitted` other than `no` is how an
 * auto-responder announces itself so that bots do not answer bots (RFC 3834).
 * A human organiser's reply carries neither.
 *
 * **Bulk** is strong evidence and nothing more. `List-Unsubscribe` (RFC 2369,
 * RFC 8058) has been required of bulk senders by Gmail and Yahoo since
 * February 2024, and `Feedback-ID` is set by most large sending platforms —
 * but **a festival that mails through Mailchimp is still a festival**, and its
 * acceptance letter would carry both. So this tier never excludes. It is here
 * to be weighed, and to be shown to somebody deciding.
 *
 * Absence proves nothing in either tier: plenty of marketing sets no headers at
 * all. This can say "certainly automated"; it can never say "certainly human".
 */

/** Header names lowercased, values verbatim. */
export type MailHeaders = Record<string, string>

export type AutomationTier = 'automated' | 'bulk' | 'unremarkable'

export interface AutomationVerdict {
  tier: AutomationTier
  /** Why, in words a person reads. Empty when nothing was found. */
  reasons: string[]
}

/** Case-insensitive lookup that treats an empty value as absent. */
function head(headers: MailHeaders, name: string): string {
  return (headers[name.toLowerCase()] ?? '').trim()
}

/**
 * Reliable by specification. Both of these are written by software declaring
 * itself, so a false positive means somebody's mail server is lying.
 */
function automatedReasons(headers: MailHeaders): string[] {
  const out: string[] = []

  if (head(headers, 'list-id')) {
    out.push('Sent by mailing list software, which only lists set.')
  }

  // RFC 3834: `no` is the explicit "this is not automatic". Anything else —
  // auto-replied, auto-generated, auto-notified — is the sender saying it is.
  const auto = head(headers, 'auto-submitted').toLowerCase()
  if (auto && auto !== 'no') {
    out.push('The sender marked it automatically generated.')
  }

  return out
}

/** Strong evidence of a bulk send, and no more than that. */
function bulkReasons(headers: MailHeaders): string[] {
  const out: string[] = []

  if (head(headers, 'list-unsubscribe') || head(headers, 'list-unsubscribe-post')) {
    out.push('Carries an unsubscribe link, which bulk senders are required to.')
  }
  if (head(headers, 'feedback-id')) {
    out.push('Sent through a bulk mailing platform.')
  }

  // RFC 2076 calls Precedence non-standard, controversial and discouraged, so
  // it is only worth reading on old mail that still sets it.
  const precedence = head(headers, 'precedence').toLowerCase()
  if (['bulk', 'list', 'junk'].includes(precedence)) {
    out.push('Marked as bulk mail by its sender.')
  }

  return out
}

export function automationVerdict(headers: MailHeaders): AutomationVerdict {
  const automated = automatedReasons(headers)
  if (automated.length) return { tier: 'automated', reasons: automated }

  const bulk = bulkReasons(headers)
  if (bulk.length) return { tier: 'bulk', reasons: bulk }

  return { tier: 'unremarkable', reasons: [] }
}

/**
 * Whether the scan should drop this without scoring it.
 *
 * Only the specification-backed tier. `bulk` deliberately survives to be
 * weighed, because the cost of being wrong differs enormously between the two:
 * dropping a mailing list loses nothing, and dropping every festival that uses
 * a mail platform loses the feature.
 */
export function isAutomated(headers: MailHeaders): boolean {
  return automationVerdict(headers).tier === 'automated'
}
