/**
 * GENERATED by scripts/generate-survey-design.ts, seed 20261005. Do not edit by hand.
 *
 * The paired-choice design for the artist survey: 24 tasks in 3 versions of
 * 8, and 6 planted pairs for the attention check. Each card is a level
 * index per attribute, in the order of ATTRIBUTES in shared/surveyInstrument.ts.
 *
 * Information (log determinant, larger is better): 52.68, against a mean of
 * 42.85 for 40 random designs that obey the same rules.
 * Level counts per attribute across all tasks: [[12,12,12,12],[12,12,12,12],[12,12,12,12],[12,12,12,12],[16,16,16],[16,16,16]].
 */

import type { Pair } from './surveyChoiceMath'

export const CHOICE_VERSIONS: Pair[][] = [
  [
    [[1, 3, 3, 1, 2, 2], [3, 2, 1, 0, 1, 0]],
    [[0, 2, 2, 3, 2, 0], [2, 1, 1, 2, 0, 2]],
    [[0, 1, 3, 3, 0, 0], [1, 0, 1, 0, 2, 1]],
    [[2, 3, 2, 0, 2, 1], [1, 2, 0, 2, 0, 2]],
    [[3, 0, 0, 0, 0, 1], [0, 2, 2, 2, 1, 2]],
    [[2, 3, 3, 2, 1, 0], [3, 1, 0, 1, 2, 2]],
    [[3, 3, 0, 1, 1, 1], [1, 0, 2, 3, 0, 2]],
    [[2, 0, 3, 3, 1, 0], [0, 3, 1, 1, 2, 1]],
  ],
  [
    [[1, 2, 1, 1, 1, 2], [0, 1, 3, 2, 0, 0]],
    [[1, 1, 0, 0, 2, 0], [3, 0, 1, 3, 0, 2]],
    [[2, 2, 2, 2, 2, 0], [0, 1, 3, 0, 1, 2]],
    [[3, 0, 2, 2, 1, 1], [1, 3, 1, 3, 0, 0]],
    [[2, 1, 1, 3, 2, 1], [3, 3, 2, 0, 0, 2]],
    [[1, 3, 0, 3, 0, 1], [2, 0, 3, 1, 2, 0]],
    [[3, 1, 2, 1, 1, 2], [2, 0, 0, 2, 2, 1]],
    [[3, 3, 0, 1, 1, 0], [0, 2, 3, 0, 0, 1]],
  ],
  [
    [[0, 1, 0, 0, 2, 2], [1, 2, 3, 1, 1, 1]],
    [[3, 2, 2, 2, 2, 2], [0, 0, 1, 1, 1, 0]],
    [[1, 1, 3, 3, 1, 2], [0, 3, 1, 2, 0, 2]],
    [[2, 1, 1, 0, 0, 0], [0, 0, 0, 3, 1, 1]],
    [[0, 0, 2, 2, 0, 0], [3, 3, 3, 3, 2, 1]],
    [[2, 2, 0, 1, 0, 1], [1, 0, 1, 2, 2, 0]],
    [[1, 1, 2, 1, 0, 1], [2, 2, 0, 0, 1, 2]],
    [[2, 3, 2, 3, 1, 1], [3, 2, 3, 0, 2, 0]],
  ],
]

/** The first card of each is better on three or more rows and no worse on any. */
export const CHECK_PAIRS: Pair[] = [
  [[0, 0, 0, 1, 2, 0], [0, 1, 0, 1, 1, 2]],
  [[2, 0, 1, 0, 2, 0], [2, 1, 2, 0, 1, 0]],
  [[2, 0, 0, 3, 0, 1], [2, 1, 1, 1, 0, 1]],
  [[0, 1, 0, 3, 2, 0], [0, 1, 2, 2, 1, 0]],
  [[3, 1, 0, 3, 2, 0], [2, 2, 2, 3, 2, 0]],
  [[2, 2, 0, 3, 2, 1], [1, 2, 1, 3, 1, 1]],
]
