// Generated by scripts/themes/derive.mjs. Edit the script, then run it with --write;
// do not edit this file by hand. The default theme is drawn by hand in themeSunDogs.ts.
//
// Each token is "r g b" channels, as the stylesheet stores them, with the hex beside it.

export const DERIVED_THEME_DATA = {
  'pebble': {
    light: {
      tokens: {
        'canvas': '236 242 233', // #ECF2E9
        'surface': '248 251 246', // #F8FBF6
        'raised': '243 247 240', // #F3F7F0
        'sunken': '226 233 222', // #E2E9DE
        'line': '208 215 204', // #D0D7CC
        'line-strong': '170 176 166', // #AAB0A6
        'field-line': '125 130 121', // #7D8279
        'ink': '26 34 22', // #1A2216
        'body': '52 60 49', // #343C31
        'muted': '82 91 79', // #525B4F
        'faint': '93 102 90', // #5D665A
        'accent': '43 99 92', // #2B635C
        'accent-hover': '21 79 73', // #154F49
        'accent-fg': '248 251 246', // #F8FBF6
        'accent-soft': '217 232 230', // #D9E8E6
        'danger-bg': '255 233 229', // #FFE9E5
        'danger-bg-hover': '248 217 212', // #F8D9D4
        'danger-line': '243 192 183', // #F3C0B7
        'danger-fg': '85 18 11', // #55120B
        'danger-solid': '167 70 57', // #A74639
        'success-bg': '225 239 236', // #E1EFEC
        'success-bg-hover': '210 226 223', // #D2E2DF
        'success-line': '182 201 197', // #B6C9C5
        'success-fg': '43 99 92', // #2B635C
        'success-solid': '43 99 92', // #2B635C
        'warn-bg': '255 228 179', // #FFE4B3
        'warn-line': '222 183 122', // #DEB77A
        'warn-fg': '138 96 10', // #8A600A
        'info-bg': '243 247 240', // #F3F7F0
        'info-bg-hover': '232 237 229', // #E8EDE5
        'info-line': '208 215 204', // #D0D7CC
        'info-fg': '43 99 92', // #2B635C
        'cat-violet-bg': '243 247 240', // #F3F7F0
        'cat-violet-line': '208 215 204', // #D0D7CC
        'cat-violet-fg': '82 91 79', // #525B4F
        'cat-sky-bg': '243 247 240', // #F3F7F0
        'cat-sky-line': '208 215 204', // #D0D7CC
        'cat-sky-fg': '82 91 79', // #525B4F
        'cat-teal-bg': '243 247 240', // #F3F7F0
        'cat-teal-line': '208 215 204', // #D0D7CC
        'cat-teal-fg': '82 91 79', // #525B4F
        'cat-orange-bg': '243 247 240', // #F3F7F0
        'cat-orange-line': '208 215 204', // #D0D7CC
        'cat-orange-fg': '82 91 79', // #525B4F
        'cat-rose-bg': '243 247 240', // #F3F7F0
        'cat-rose-line': '208 215 204', // #D0D7CC
        'cat-rose-fg': '82 91 79', // #525B4F
        'scrim': '26 34 22', // #1A2216
      },
      highContrast: {
        'line': '121 128 117', // #798075
        'line-strong': '95 101 92', // #5F655C
        'field-line': '95 101 92', // #5F655C
        'body': '33 41 30', // #21291E
        'muted': '56 64 53', // #384035
        'faint': '66 75 63', // #424B3F
      },
      shadow: {
        card: '0 1px 2px rgba(26,34,22,.07)',
        raised: '0 2px 4px rgba(26,34,22,.06), 0 10px 26px -10px rgba(26,34,22,.17)',
        pop: '0 8px 12px -4px rgba(26,34,22,.10), 0 18px 36px -12px rgba(26,34,22,.22)',
        inset: 'inset 0 1px 0 rgba(248,251,246,.8)',
      },
    },
    dark: {
      tokens: {
        'canvas': '14 16 13', // #0E100D
        'surface': '22 24 20', // #161814
        'raised': '31 33 29', // #1F211D
        'sunken': '9 11 8', // #090B08
        'line': '44 47 42', // #2C2F2A
        'line-strong': '70 73 68', // #464944
        'field-line': '107 113 104', // #6B7168
        'ink': '227 239 223', // #E3EFDF
        'body': '183 193 179', // #B7C1B3
        'muted': '149 159 145', // #959F91
        'faint': '131 141 127', // #838D7F
        'accent': '152 209 200', // #98D1C8
        'accent-hover': '171 229 220', // #ABE5DC
        'accent-fg': '21 23 19', // #151713
        'accent-soft': '22 37 35', // #162523
        'danger-bg': '46 25 21', // #2E1915
        'danger-bg-hover': '58 33 29', // #3A211D
        'danger-line': '83 43 37', // #532B25
        'danger-fg': '193 116 104', // #C17468
        'danger-solid': '187 88 74', // #BB584A
        'success-bg': '22 34 32', // #162220
        'success-bg-hover': '30 44 42', // #1E2C2A
        'success-line': '39 54 52', // #273634
        'success-fg': '152 209 200', // #98D1C8
        'success-solid': '85 140 132', // #558C84
        'warn-bg': '44 31 9', // #2C1F09
        'warn-line': '78 57 20', // #4E3914
        'warn-fg': '254 207 134', // #FECF86
        'info-bg': '31 33 29', // #1F211D
        'info-bg-hover': '37 39 35', // #252723
        'info-line': '44 47 42', // #2C2F2A
        'info-fg': '152 209 200', // #98D1C8
        'cat-violet-bg': '31 33 29', // #1F211D
        'cat-violet-line': '44 47 42', // #2C2F2A
        'cat-violet-fg': '149 159 145', // #959F91
        'cat-sky-bg': '31 33 29', // #1F211D
        'cat-sky-line': '44 47 42', // #2C2F2A
        'cat-sky-fg': '149 159 145', // #959F91
        'cat-teal-bg': '31 33 29', // #1F211D
        'cat-teal-line': '44 47 42', // #2C2F2A
        'cat-teal-fg': '149 159 145', // #959F91
        'cat-orange-bg': '31 33 29', // #1F211D
        'cat-orange-line': '44 47 42', // #2C2F2A
        'cat-orange-fg': '149 159 145', // #959F91
        'cat-rose-bg': '31 33 29', // #1F211D
        'cat-rose-line': '44 47 42', // #2C2F2A
        'cat-rose-fg': '149 159 145', // #959F91
        'scrim': '0 0 0', // #000000
      },
      highContrast: {
        'line': '107 113 103', // #6B7167
        'line-strong': '136 142 132', // #888E84
        'field-line': '136 142 132', // #888E84
        'body': '215 226 211', // #D7E2D3
        'muted': '196 206 192', // #C4CEC0
        'faint': '183 193 179', // #B7C1B3
      },
      shadow: {
        card: '0 1px 0 rgba(255,255,255,.03) inset, 0 2px 8px rgba(0,0,0,.5)',
        raised: '0 1px 0 rgba(255,255,255,.04) inset, 0 6px 20px -6px rgba(0,0,0,.7)',
        pop: '0 1px 0 rgba(255,255,255,.05) inset, 0 12px 34px -10px rgba(0,0,0,.82)',
        inset: 'inset 0 1px 0 rgba(255,255,255,.04)',
      },
    },
  },
  'opal': {
    light: {
      tokens: {
        'canvas': '246 239 231', // #F6EFE7
        'surface': '253 249 246', // #FDF9F6
        'raised': '249 244 239', // #F9F4EF
        'sunken': '237 229 220', // #EDE5DC
        'line': '219 211 202', // #DBD3CA
        'line-strong': '181 172 164', // #B5ACA4
        'field-line': '134 127 119', // #867F77
        'ink': '21 35 27', // #15231B
        'body': '48 61 53', // #303D35
        'muted': '78 92 83', // #4E5C53
        'faint': '89 103 94', // #59675E
        'accent': '35 116 77', // #23744D
        'accent-hover': '1 96 58', // #01603A
        'accent-fg': '253 249 246', // #FDF9F6
        'accent-soft': '214 235 222', // #D6EBDE
        'danger-bg': '255 233 229', // #FFE9E5
        'danger-bg-hover': '248 217 212', // #F8D9D4
        'danger-line': '243 192 183', // #F3C0B7
        'danger-fg': '85 18 11', // #55120B
        'danger-solid': '167 70 57', // #A74639
        'success-bg': '222 241 229', // #DEF1E5
        'success-bg-hover': '206 228 215', // #CEE4D7
        'success-line': '178 203 188', // #B2CBBC
        'success-fg': '35 116 77', // #23744D
        'success-solid': '35 116 77', // #23744D
        'warn-bg': '255 228 179', // #FFE4B3
        'warn-line': '222 183 122', // #DEB77A
        'warn-fg': '129 91 17', // #815B11
        'info-bg': '249 244 239', // #F9F4EF
        'info-bg-hover': '241 234 227', // #F1EAE3
        'info-line': '219 211 202', // #DBD3CA
        'info-fg': '35 116 77', // #23744D
        'cat-violet-bg': '249 244 239', // #F9F4EF
        'cat-violet-line': '219 211 202', // #DBD3CA
        'cat-violet-fg': '78 92 83', // #4E5C53
        'cat-sky-bg': '249 244 239', // #F9F4EF
        'cat-sky-line': '219 211 202', // #DBD3CA
        'cat-sky-fg': '78 92 83', // #4E5C53
        'cat-teal-bg': '249 244 239', // #F9F4EF
        'cat-teal-line': '219 211 202', // #DBD3CA
        'cat-teal-fg': '78 92 83', // #4E5C53
        'cat-orange-bg': '249 244 239', // #F9F4EF
        'cat-orange-line': '219 211 202', // #DBD3CA
        'cat-orange-fg': '78 92 83', // #4E5C53
        'cat-rose-bg': '249 244 239', // #F9F4EF
        'cat-rose-line': '219 211 202', // #DBD3CA
        'cat-rose-fg': '78 92 83', // #4E5C53
        'scrim': '21 35 27', // #15231B
      },
      highContrast: {
        'line': '135 127 119', // #877F77
        'line-strong': '105 98 90', // #69625A
        'field-line': '105 98 90', // #69625A
        'body': '29 42 34', // #1D2A22
        'muted': '51 65 57', // #334139
        'faint': '62 76 67', // #3E4C43
      },
      shadow: {
        card: '0 1px 2px rgba(21,35,27,.07)',
        raised: '0 2px 4px rgba(21,35,27,.06), 0 10px 26px -10px rgba(21,35,27,.17)',
        pop: '0 8px 12px -4px rgba(21,35,27,.10), 0 18px 36px -12px rgba(21,35,27,.22)',
        inset: 'inset 0 1px 0 rgba(253,249,246,.8)',
      },
    },
    dark: {
      tokens: {
        'canvas': '18 15 12', // #120F0C
        'surface': '26 23 19', // #1A1713
        'raised': '35 32 29', // #23201D
        'sunken': '12 10 7', // #0C0A07
        'line': '49 45 41', // #312D29
        'line-strong': '75 71 67', // #4B4743
        'field-line': '116 109 102', // #746D66
        'ink': '222 241 229', // #DEF1E5
        'body': '178 194 184', // #B2C2B8
        'muted': '144 160 150', // #90A096
        'faint': '126 142 132', // #7E8E84
        'accent': '138 216 172', // #8AD8AC
        'accent-hover': '157 236 191', // #9DECBF
        'accent-fg': '24 21 18', // #181512
        'accent-soft': '18 39 27', // #12271B
        'danger-bg': '46 25 21', // #2E1915
        'danger-bg-hover': '58 33 29', // #3A211D
        'danger-line': '83 43 37', // #532B25
        'danger-fg': '193 116 104', // #C17468
        'danger-solid': '187 88 74', // #BB584A
        'success-bg': '18 36 26', // #12241A
        'success-bg-hover': '26 46 35', // #1A2E23
        'success-line': '35 56 44', // #23382C
        'success-fg': '138 216 172', // #8AD8AC
        'success-solid': '69 146 105', // #459269
        'warn-bg': '44 31 9', // #2C1F09
        'warn-line': '78 57 20', // #4E3914
        'warn-fg': '227 181 109', // #E3B56D
        'info-bg': '35 32 29', // #23201D
        'info-bg-hover': '41 38 34', // #292622
        'info-line': '49 45 41', // #312D29
        'info-fg': '138 216 172', // #8AD8AC
        'cat-violet-bg': '35 32 29', // #23201D
        'cat-violet-line': '49 45 41', // #312D29
        'cat-violet-fg': '144 160 150', // #90A096
        'cat-sky-bg': '35 32 29', // #23201D
        'cat-sky-line': '49 45 41', // #312D29
        'cat-sky-fg': '144 160 150', // #90A096
        'cat-teal-bg': '35 32 29', // #23201D
        'cat-teal-line': '49 45 41', // #312D29
        'cat-teal-fg': '144 160 150', // #90A096
        'cat-orange-bg': '35 32 29', // #23201D
        'cat-orange-line': '49 45 41', // #312D29
        'cat-orange-fg': '144 160 150', // #90A096
        'cat-rose-bg': '35 32 29', // #23201D
        'cat-rose-line': '49 45 41', // #312D29
        'cat-rose-fg': '144 160 150', // #90A096
        'scrim': '0 0 0', // #000000
      },
      highContrast: {
        'line': '117 109 101', // #756D65
        'line-strong': '147 139 130', // #938B82
        'field-line': '147 139 130', // #938B82
        'body': '210 227 216', // #D2E3D8
        'muted': '191 207 197', // #BFCFC5
        'faint': '178 194 184', // #B2C2B8
      },
      shadow: {
        card: '0 1px 0 rgba(255,255,255,.03) inset, 0 2px 8px rgba(0,0,0,.5)',
        raised: '0 1px 0 rgba(255,255,255,.04) inset, 0 6px 20px -6px rgba(0,0,0,.7)',
        pop: '0 1px 0 rgba(255,255,255,.05) inset, 0 12px 34px -10px rgba(0,0,0,.82)',
        inset: 'inset 0 1px 0 rgba(255,255,255,.04)',
      },
    },
  },
  'harvest': {
    light: {
      tokens: {
        'canvas': '238 242 226', // #EEF2E2
        'surface': '249 251 243', // #F9FBF3
        'raised': '244 247 235', // #F4F7EB
        'sunken': '228 233 215', // #E4E9D7
        'line': '210 215 196', // #D2D7C4
        'line-strong': '172 176 158', // #ACB09E
        'field-line': '127 130 114', // #7F8272
        'ink': '24 34 23', // #182217
        'body': '51 60 50', // #333C32
        'muted': '81 91 80', // #515B50
        'faint': '92 103 91', // #5C675B
        'accent': '58 115 53', // #3A7335
        'accent-hover': '38 94 34', // #265E22
        'accent-fg': '249 251 243', // #F9FBF3
        'accent-soft': '217 234 215', // #D9EAD7
        'danger-bg': '255 233 229', // #FFE9E5
        'danger-bg-hover': '248 217 212', // #F8D9D4
        'danger-line': '243 192 183', // #F3C0B7
        'danger-fg': '85 18 11', // #55120B
        'danger-solid': '167 70 57', // #A74639
        'success-bg': '225 240 223', // #E1F0DF
        'success-bg-hover': '210 228 208', // #D2E4D0
        'success-line': '183 203 180', // #B7CBB4
        'success-fg': '58 115 53', // #3A7335
        'success-solid': '58 115 53', // #3A7335
        'warn-bg': '255 228 179', // #FFE4B3
        'warn-line': '222 183 122', // #DEB77A
        'warn-fg': '138 96 10', // #8A600A
        'info-bg': '244 247 235', // #F4F7EB
        'info-bg-hover': '234 237 223', // #EAEDDF
        'info-line': '210 215 196', // #D2D7C4
        'info-fg': '58 115 53', // #3A7335
        'cat-violet-bg': '244 247 235', // #F4F7EB
        'cat-violet-line': '210 215 196', // #D2D7C4
        'cat-violet-fg': '81 91 80', // #515B50
        'cat-sky-bg': '244 247 235', // #F4F7EB
        'cat-sky-line': '210 215 196', // #D2D7C4
        'cat-sky-fg': '81 91 80', // #515B50
        'cat-teal-bg': '244 247 235', // #F4F7EB
        'cat-teal-line': '210 215 196', // #D2D7C4
        'cat-teal-fg': '81 91 80', // #515B50
        'cat-orange-bg': '244 247 235', // #F4F7EB
        'cat-orange-line': '210 215 196', // #D2D7C4
        'cat-orange-fg': '81 91 80', // #515B50
        'cat-rose-bg': '244 247 235', // #F4F7EB
        'cat-rose-line': '210 215 196', // #D2D7C4
        'cat-rose-fg': '81 91 80', // #515B50
        'scrim': '24 34 23', // #182217
      },
      highContrast: {
        'line': '124 128 110', // #7C806E
        'line-strong': '98 101 85', // #626555
        'field-line': '98 101 85', // #626555
        'body': '32 41 31', // #20291F
        'muted': '55 64 53', // #374035
        'faint': '65 75 64', // #414B40
      },
      shadow: {
        card: '0 1px 2px rgba(24,34,23,.07)',
        raised: '0 2px 4px rgba(24,34,23,.06), 0 10px 26px -10px rgba(24,34,23,.17)',
        pop: '0 8px 12px -4px rgba(24,34,23,.10), 0 18px 36px -12px rgba(24,34,23,.22)',
        inset: 'inset 0 1px 0 rgba(249,251,243,.8)',
      },
    },
    dark: {
      tokens: {
        'canvas': '15 16 10', // #0F100A
        'surface': '23 24 17', // #171811
        'raised': '32 33 26', // #20211A
        'sunken': '10 11 5', // #0A0B05
        'line': '45 47 38', // #2D2F26
        'line-strong': '71 73 64', // #474940
        'field-line': '109 113 97', // #6D7161
        'ink': '226 240 224', // #E2F0E0
        'body': '182 194 180', // #B6C2B4
        'muted': '148 159 146', // #949F92
        'faint': '130 141 128', // #828D80
        'accent': '155 215 148', // #9BD794
        'accent-hover': '174 235 167', // #AEEBA7
        'accent-fg': '21 23 16', // #151710
        'accent-soft': '23 38 21', // #172615
        'danger-bg': '46 25 21', // #2E1915
        'danger-bg-hover': '58 33 29', // #3A211D
        'danger-line': '83 43 37', // #532B25
        'danger-fg': '193 116 104', // #C17468
        'danger-solid': '187 88 74', // #BB584A
        'success-bg': '22 35 21', // #162315
        'success-bg-hover': '30 45 29', // #1E2D1D
        'success-line': '39 56 38', // #273826
        'success-fg': '155 215 148', // #9BD794
        'success-solid': '88 145 82', // #589152
        'warn-bg': '44 31 9', // #2C1F09
        'warn-line': '78 57 20', // #4E3914
        'warn-fg': '214 169 96', // #D6A960
        'info-bg': '32 33 26', // #20211A
        'info-bg-hover': '38 39 32', // #262720
        'info-line': '45 47 38', // #2D2F26
        'info-fg': '155 215 148', // #9BD794
        'cat-violet-bg': '32 33 26', // #20211A
        'cat-violet-line': '45 47 38', // #2D2F26
        'cat-violet-fg': '148 159 146', // #949F92
        'cat-sky-bg': '32 33 26', // #20211A
        'cat-sky-line': '45 47 38', // #2D2F26
        'cat-sky-fg': '148 159 146', // #949F92
        'cat-teal-bg': '32 33 26', // #20211A
        'cat-teal-line': '45 47 38', // #2D2F26
        'cat-teal-fg': '148 159 146', // #949F92
        'cat-orange-bg': '32 33 26', // #20211A
        'cat-orange-line': '45 47 38', // #2D2F26
        'cat-orange-fg': '148 159 146', // #949F92
        'cat-rose-bg': '32 33 26', // #20211A
        'cat-rose-line': '45 47 38', // #2D2F26
        'cat-rose-fg': '148 159 146', // #949F92
        'scrim': '0 0 0', // #000000
      },
      highContrast: {
        'line': '109 113 96', // #6D7160
        'line-strong': '138 143 125', // #8A8F7D
        'field-line': '138 143 125', // #8A8F7D
        'body': '214 226 212', // #D6E2D4
        'muted': '195 206 193', // #C3CEC1
        'faint': '182 194 180', // #B6C2B4
      },
      shadow: {
        card: '0 1px 0 rgba(255,255,255,.03) inset, 0 2px 8px rgba(0,0,0,.5)',
        raised: '0 1px 0 rgba(255,255,255,.04) inset, 0 6px 20px -6px rgba(0,0,0,.7)',
        pop: '0 1px 0 rgba(255,255,255,.05) inset, 0 12px 34px -10px rgba(0,0,0,.82)',
        inset: 'inset 0 1px 0 rgba(255,255,255,.04)',
      },
    },
  },
  'high-contrast': {
    light: {
      tokens: {
        'canvas': '255 255 255', // #FFFFFF
        'surface': '255 255 255', // #FFFFFF
        'raised': '243 243 243', // #F3F3F3
        'sunken': '232 232 232', // #E8E8E8
        'line': '128 128 128', // #808080
        'line-strong': '102 102 102', // #666666
        'field-line': '102 102 102', // #666666
        'ink': '31 31 31', // #1F1F1F
        'body': '57 57 57', // #393939
        'muted': '74 74 74', // #4A4A4A
        'faint': '74 74 74', // #4A4A4A
        'accent': '3 66 99', // #034263
        'accent-hover': '2 47 72', // #022F48
        'accent-fg': '250 250 250', // #FAFAFA
        'accent-soft': '213 232 246', // #D5E8F6
        'danger-bg': '254 233 232', // #FEE9E8
        'danger-bg-hover': '248 217 216', // #F8D9D8
        'danger-line': '243 191 190', // #F3BFBE
        'danger-fg': '130 43 49', // #822B31
        'danger-solid': '167 68 73', // #A74449
        'success-bg': '221 238 251', // #DDEEFB
        'success-bg-hover': '205 225 240', // #CDE1F0
        'success-line': '177 200 217', // #B1C8D9
        'success-fg': '3 66 99', // #034263
        'success-solid': '3 66 99', // #034263
        'warn-bg': '254 227 194', // #FEE3C2
        'warn-line': '229 179 126', // #E5B37E
        'warn-fg': '106 63 0', // #6A3F00
        'info-bg': '243 243 243', // #F3F3F3
        'info-bg-hover': '235 235 235', // #EBEBEB
        'info-line': '128 128 128', // #808080
        'info-fg': '3 66 99', // #034263
        'cat-violet-bg': '243 243 243', // #F3F3F3
        'cat-violet-line': '128 128 128', // #808080
        'cat-violet-fg': '74 74 74', // #4A4A4A
        'cat-sky-bg': '243 243 243', // #F3F3F3
        'cat-sky-line': '128 128 128', // #808080
        'cat-sky-fg': '74 74 74', // #4A4A4A
        'cat-teal-bg': '243 243 243', // #F3F3F3
        'cat-teal-line': '128 128 128', // #808080
        'cat-teal-fg': '74 74 74', // #4A4A4A
        'cat-orange-bg': '243 243 243', // #F3F3F3
        'cat-orange-line': '128 128 128', // #808080
        'cat-orange-fg': '74 74 74', // #4A4A4A
        'cat-rose-bg': '243 243 243', // #F3F3F3
        'cat-rose-line': '128 128 128', // #808080
        'cat-rose-fg': '74 74 74', // #4A4A4A
        'scrim': '31 31 31', // #1F1F1F
      },
      highContrast: null,
      shadow: {
        card: '0 1px 2px rgba(31,31,31,.07)',
        raised: '0 2px 4px rgba(31,31,31,.06), 0 10px 26px -10px rgba(31,31,31,.17)',
        pop: '0 8px 12px -4px rgba(31,31,31,.10), 0 18px 36px -12px rgba(31,31,31,.22)',
        inset: 'inset 0 1px 0 rgba(255,255,255,.8)',
      },
    },
    dark: {
      tokens: {
        'canvas': '0 0 0', // #000000
        'surface': '3 3 3', // #030303
        'raised': '13 13 13', // #0D0D0D
        'sunken': '1 1 1', // #010101
        'line': '99 99 99', // #636363
        'line-strong': '125 125 125', // #7D7D7D
        'field-line': '125 125 125', // #7D7D7D
        'ink': '235 235 235', // #EBEBEB
        'body': '190 190 190', // #BEBEBE
        'muted': '174 174 174', // #AEAEAE
        'faint': '174 174 174', // #AEAEAE
        'accent': '128 199 248', // #80C7F8
        'accent-hover': '165 217 254', // #A5D9FE
        'accent-fg': '22 22 22', // #161616
        'accent-soft': '17 36 49', // #112431
        'danger-bg': '46 24 24', // #2E1818
        'danger-bg-hover': '58 33 33', // #3A2121
        'danger-line': '83 42 43', // #532A2B
        'danger-fg': '244 145 145', // #F49191
        'danger-solid': '187 86 90', // #BB565A
        'success-bg': '17 33 44', // #11212C
        'success-bg-hover': '25 43 56', // #192B38
        'success-line': '34 53 67', // #223543
        'success-fg': '128 199 248', // #80C7F8
        'success-solid': '65 136 182', // #4188B6
        'warn-bg': '42 32 9', // #2A2009
        'warn-line': '74 59 19', // #4A3B13
        'warn-fg': '251 218 139', // #FBDA8B
        'info-bg': '13 13 13', // #0D0D0D
        'info-bg-hover': '38 38 38', // #262626
        'info-line': '99 99 99', // #636363
        'info-fg': '128 199 248', // #80C7F8
        'cat-violet-bg': '13 13 13', // #0D0D0D
        'cat-violet-line': '99 99 99', // #636363
        'cat-violet-fg': '174 174 174', // #AEAEAE
        'cat-sky-bg': '13 13 13', // #0D0D0D
        'cat-sky-line': '99 99 99', // #636363
        'cat-sky-fg': '174 174 174', // #AEAEAE
        'cat-teal-bg': '13 13 13', // #0D0D0D
        'cat-teal-line': '99 99 99', // #636363
        'cat-teal-fg': '174 174 174', // #AEAEAE
        'cat-orange-bg': '13 13 13', // #0D0D0D
        'cat-orange-line': '99 99 99', // #636363
        'cat-orange-fg': '174 174 174', // #AEAEAE
        'cat-rose-bg': '13 13 13', // #0D0D0D
        'cat-rose-line': '99 99 99', // #636363
        'cat-rose-fg': '174 174 174', // #AEAEAE
        'scrim': '0 0 0', // #000000
      },
      highContrast: null,
      shadow: {
        card: '0 1px 0 rgba(255,255,255,.03) inset, 0 2px 8px rgba(0,0,0,.5)',
        raised: '0 1px 0 rgba(255,255,255,.04) inset, 0 6px 20px -6px rgba(0,0,0,.7)',
        pop: '0 1px 0 rgba(255,255,255,.05) inset, 0 12px 34px -10px rgba(0,0,0,.82)',
        inset: 'inset 0 1px 0 rgba(255,255,255,.04)',
      },
    },
  },
  'colour-blind': {
    light: {
      tokens: {
        'canvas': '245 243 239', // #F5F3EF
        'surface': '252 252 249', // #FCFCF9
        'raised': '247 247 244', // #F7F7F4
        'sunken': '236 235 230', // #ECEBE6
        'line': '213 212 207', // #D5D4CF
        'line-strong': '175 174 169', // #AFAEA9
        'field-line': '132 131 127', // #84837F
        'ink': '27 31 41', // #1B1F29
        'body': '53 57 67', // #353943
        'muted': '70 74 84', // #464A54
        'faint': '70 74 84', // #464A54
        'accent': '8 74 137', // #084A89
        'accent-hover': '0 55 107', // #00376B
        'accent-fg': '251 250 248', // #FBFAF8
        'accent-soft': '212 231 253', // #D4E7FD
        'danger-bg': '254 232 238', // #FEE8EE
        'danger-bg-hover': '246 216 224', // #F6D8E0
        'danger-line': '240 190 204', // #F0BECC
        'danger-fg': '104 8 53', // #680835
        'danger-solid': '162 68 102', // #A24466
        'success-bg': '222 237 254', // #DEEDFE
        'success-bg-hover': '204 224 248', // #CCE0F8
        'success-line': '176 199 226', // #B0C7E2
        'success-fg': '8 74 137', // #084A89
        'success-solid': '8 74 137', // #084A89
        'warn-bg': '242 234 180', // #F2EAB4
        'warn-line': '208 190 121', // #D0BE79
        'warn-fg': '89 73 0', // #594900
        'info-bg': '247 247 244', // #F7F7F4
        'info-bg-hover': '236 235 231', // #ECEBE7
        'info-line': '213 212 207', // #D5D4CF
        'info-fg': '8 74 137', // #084A89
        'cat-violet-bg': '247 247 244', // #F7F7F4
        'cat-violet-line': '213 212 207', // #D5D4CF
        'cat-violet-fg': '70 74 84', // #464A54
        'cat-sky-bg': '247 247 244', // #F7F7F4
        'cat-sky-line': '213 212 207', // #D5D4CF
        'cat-sky-fg': '70 74 84', // #464A54
        'cat-teal-bg': '247 247 244', // #F7F7F4
        'cat-teal-line': '213 212 207', // #D5D4CF
        'cat-teal-fg': '70 74 84', // #464A54
        'cat-orange-bg': '247 247 244', // #F7F7F4
        'cat-orange-line': '213 212 207', // #D5D4CF
        'cat-orange-fg': '70 74 84', // #464A54
        'cat-rose-bg': '247 247 244', // #F7F7F4
        'cat-rose-line': '213 212 207', // #D5D4CF
        'cat-rose-fg': '70 74 84', // #464A54
        'scrim': '27 31 41', // #1B1F29
      },
      highContrast: {
        'line': '129 128 123', // #81807B
        'line-strong': '100 99 95', // #64635F
        'field-line': '100 99 95', // #64635F
        'body': '34 38 47', // #22262F
        'muted': '56 61 71', // #383D47
        'faint': '67 72 82', // #434852
      },
      shadow: {
        card: '0 1px 2px rgba(27,31,41,.07)',
        raised: '0 2px 4px rgba(27,31,41,.06), 0 10px 26px -10px rgba(27,31,41,.17)',
        pop: '0 8px 12px -4px rgba(27,31,41,.10), 0 18px 36px -12px rgba(27,31,41,.22)',
        inset: 'inset 0 1px 0 rgba(252,252,249,.8)',
      },
    },
    dark: {
      tokens: {
        'canvas': '16 15 14', // #100F0E
        'surface': '24 23 21', // #181715
        'raised': '33 32 31', // #21201F
        'sunken': '11 10 8', // #0B0A08
        'line': '46 46 43', // #2E2E2B
        'line-strong': '72 72 69', // #484845
        'field-line': '112 111 106', // #706F6A
        'ink': '229 235 249', // #E5EBF9
        'body': '184 190 202', // #B8BECA
        'muted': '168 174 186', // #A8AEBA
        'faint': '168 174 186', // #A8AEBA
        'accent': '136 172 251', // #88ACFB
        'accent-hover': '164 192 252', // #A4C0FC
        'accent-fg': '22 22 20', // #161614
        'accent-soft': '23 33 55', // #172137
        'danger-bg': '46 24 27', // #2E181B
        'danger-bg-hover': '58 32 36', // #3A2024
        'danger-line': '82 42 49', // #522A31
        'danger-fg': '247 140 158', // #F78C9E
        'danger-solid': '185 85 105', // #B95569
        'success-bg': '22 31 50', // #161F32
        'success-bg-hover': '30 40 62', // #1E283E
        'success-line': '39 50 74', // #27324A
        'success-fg': '136 172 251', // #88ACFB
        'success-solid': '90 125 206', // #5A7DCE
        'warn-bg': '36 35 10', // #24230A
        'warn-line': '66 63 21', // #423F15
        'warn-fg': '209 201 93', // #D1C95D
        'info-bg': '33 32 31', // #21201F
        'info-bg-hover': '39 38 36', // #272624
        'info-line': '46 46 43', // #2E2E2B
        'info-fg': '136 172 251', // #88ACFB
        'cat-violet-bg': '33 32 31', // #21201F
        'cat-violet-line': '46 46 43', // #2E2E2B
        'cat-violet-fg': '168 174 186', // #A8AEBA
        'cat-sky-bg': '33 32 31', // #21201F
        'cat-sky-line': '46 46 43', // #2E2E2B
        'cat-sky-fg': '168 174 186', // #A8AEBA
        'cat-teal-bg': '33 32 31', // #21201F
        'cat-teal-line': '46 46 43', // #2E2E2B
        'cat-teal-fg': '168 174 186', // #A8AEBA
        'cat-orange-bg': '33 32 31', // #21201F
        'cat-orange-line': '46 46 43', // #2E2E2B
        'cat-orange-fg': '168 174 186', // #A8AEBA
        'cat-rose-bg': '33 32 31', // #21201F
        'cat-rose-line': '46 46 43', // #2E2E2B
        'cat-rose-fg': '168 174 186', // #A8AEBA
        'scrim': '0 0 0', // #000000
      },
      highContrast: {
        'line': '112 111 106', // #706F6A
        'line-strong': '141 140 135', // #8D8C87
        'field-line': '141 140 135', // #8D8C87
        'body': '216 222 234', // #D8DEEA
        'muted': '197 203 215', // #C5CBD7
        'faint': '184 190 202', // #B8BECA
      },
      shadow: {
        card: '0 1px 0 rgba(255,255,255,.03) inset, 0 2px 8px rgba(0,0,0,.5)',
        raised: '0 1px 0 rgba(255,255,255,.04) inset, 0 6px 20px -6px rgba(0,0,0,.7)',
        pop: '0 1px 0 rgba(255,255,255,.05) inset, 0 12px 34px -10px rgba(0,0,0,.82)',
        inset: 'inset 0 1px 0 rgba(255,255,255,.04)',
      },
    },
  },
  'greyscale': {
    light: {
      tokens: {
        'canvas': '245 245 245', // #F5F5F5
        'surface': '253 253 253', // #FDFDFD
        'raised': '248 248 248', // #F8F8F8
        'sunken': '235 235 235', // #EBEBEB
        'line': '212 212 212', // #D4D4D4
        'line-strong': '174 174 174', // #AEAEAE
        'field-line': '131 131 131', // #838383
        'ink': '31 31 31', // #1F1F1F
        'body': '57 57 57', // #393939
        'muted': '72 72 72', // #484848
        'faint': '72 72 72', // #484848
        'accent': '61 61 61', // #3D3D3D
        'accent-hover': '43 43 43', // #2B2B2B
        'accent-fg': '250 250 250', // #FAFAFA
        'accent-soft': '228 228 228', // #E4E4E4
        'danger-bg': '238 238 238', // #EEEEEE
        'danger-bg-hover': '225 225 225', // #E1E1E1
        'danger-line': '206 206 206', // #CECECE
        'danger-fg': '27 27 27', // #1B1B1B
        'danger-solid': '105 105 105', // #696969
        'success-bg': '235 235 235', // #EBEBEB
        'success-bg-hover': '222 222 222', // #DEDEDE
        'success-line': '196 196 196', // #C4C4C4
        'success-fg': '61 61 61', // #3D3D3D
        'success-solid': '61 61 61', // #3D3D3D
        'warn-bg': '232 232 232', // #E8E8E8
        'warn-line': '190 190 190', // #BEBEBE
        'warn-fg': '102 102 102', // #666666
        'info-bg': '248 248 248', // #F8F8F8
        'info-bg-hover': '235 235 235', // #EBEBEB
        'info-line': '212 212 212', // #D4D4D4
        'info-fg': '61 61 61', // #3D3D3D
        'cat-violet-bg': '248 248 248', // #F8F8F8
        'cat-violet-line': '212 212 212', // #D4D4D4
        'cat-violet-fg': '72 72 72', // #484848
        'cat-sky-bg': '248 248 248', // #F8F8F8
        'cat-sky-line': '212 212 212', // #D4D4D4
        'cat-sky-fg': '72 72 72', // #484848
        'cat-teal-bg': '248 248 248', // #F8F8F8
        'cat-teal-line': '212 212 212', // #D4D4D4
        'cat-teal-fg': '72 72 72', // #484848
        'cat-orange-bg': '248 248 248', // #F8F8F8
        'cat-orange-line': '212 212 212', // #D4D4D4
        'cat-orange-fg': '72 72 72', // #484848
        'cat-rose-bg': '248 248 248', // #F8F8F8
        'cat-rose-line': '212 212 212', // #D4D4D4
        'cat-rose-fg': '72 72 72', // #484848
        'scrim': '31 31 31', // #1F1F1F
      },
      highContrast: {
        'line': '128 128 128', // #808080
        'line-strong': '99 99 99', // #636363
        'field-line': '99 99 99', // #636363
        'body': '38 38 38', // #262626
        'muted': '61 61 61', // #3D3D3D
        'faint': '69 69 69', // #454545
      },
      shadow: {
        card: '0 1px 2px rgba(31,31,31,.07)',
        raised: '0 2px 4px rgba(31,31,31,.06), 0 10px 26px -10px rgba(31,31,31,.17)',
        pop: '0 8px 12px -4px rgba(31,31,31,.10), 0 18px 36px -12px rgba(31,31,31,.22)',
        inset: 'inset 0 1px 0 rgba(253,253,253,.8)',
      },
    },
    dark: {
      tokens: {
        'canvas': '11 11 11', // #0B0B0B
        'surface': '19 19 19', // #131313
        'raised': '25 25 25', // #191919
        'sunken': '6 6 6', // #060606
        'line': '46 46 46', // #2E2E2E
        'line-strong': '72 72 72', // #484848
        'field-line': '105 105 105', // #696969
        'ink': '235 235 235', // #EBEBEB
        'body': '190 190 190', // #BEBEBE
        'muted': '174 174 174', // #AEAEAE
        'faint': '174 174 174', // #AEAEAE
        'accent': '177 177 177', // #B1B1B1
        'accent-hover': '196 196 196', // #C4C4C4
        'accent-fg': '22 22 22', // #161616
        'accent-soft': '34 34 34', // #222222
        'danger-bg': '31 31 31', // #1F1F1F
        'danger-bg-hover': '41 41 41', // #292929
        'danger-line': '56 56 56', // #383838
        'danger-fg': '228 228 228', // #E4E4E4
        'danger-solid': '122 122 122', // #7A7A7A
        'success-bg': '31 31 31', // #1F1F1F
        'success-bg-hover': '41 41 41', // #292929
        'success-line': '51 51 51', // #333333
        'success-fg': '177 177 177', // #B1B1B1
        'success-solid': '128 128 128', // #808080
        'warn-bg': '34 34 34', // #222222
        'warn-line': '61 61 61', // #3D3D3D
        'warn-fg': '137 137 137', // #898989
        'info-bg': '25 25 25', // #191919
        'info-bg-hover': '38 38 38', // #262626
        'info-line': '46 46 46', // #2E2E2E
        'info-fg': '177 177 177', // #B1B1B1
        'cat-violet-bg': '25 25 25', // #191919
        'cat-violet-line': '46 46 46', // #2E2E2E
        'cat-violet-fg': '174 174 174', // #AEAEAE
        'cat-sky-bg': '25 25 25', // #191919
        'cat-sky-line': '46 46 46', // #2E2E2E
        'cat-sky-fg': '174 174 174', // #AEAEAE
        'cat-teal-bg': '25 25 25', // #191919
        'cat-teal-line': '46 46 46', // #2E2E2E
        'cat-teal-fg': '174 174 174', // #AEAEAE
        'cat-orange-bg': '25 25 25', // #191919
        'cat-orange-line': '46 46 46', // #2E2E2E
        'cat-orange-fg': '174 174 174', // #AEAEAE
        'cat-rose-bg': '25 25 25', // #191919
        'cat-rose-line': '46 46 46', // #2E2E2E
        'cat-rose-fg': '174 174 174', // #AEAEAE
        'scrim': '0 0 0', // #000000
      },
      highContrast: {
        'line': '111 111 111', // #6F6F6F
        'line-strong': '140 140 140', // #8C8C8C
        'field-line': '140 140 140', // #8C8C8C
        'body': '222 222 222', // #DEDEDE
        'muted': '202 202 202', // #CACACA
        'faint': '190 190 190', // #BEBEBE
      },
      shadow: {
        card: '0 1px 0 rgba(255,255,255,.03) inset, 0 2px 8px rgba(0,0,0,.5)',
        raised: '0 1px 0 rgba(255,255,255,.04) inset, 0 6px 20px -6px rgba(0,0,0,.7)',
        pop: '0 1px 0 rgba(255,255,255,.05) inset, 0 12px 34px -10px rgba(0,0,0,.82)',
        inset: 'inset 0 1px 0 rgba(255,255,255,.04)',
      },
    },
  },
  'low-glare': {
    light: {
      tokens: {
        'canvas': '220 209 195', // #DCD1C3
        'surface': '227 221 214', // #E3DDD6
        'raised': '224 216 206', // #E0D8CE
        'sunken': '208 196 181', // #D0C4B5
        'line': '223 210 194', // #DFD2C2
        'line-strong': '185 172 156', // #B9AC9C
        'field-line': '114 103 90', // #72675A
        'ink': '57 46 39', // #392E27
        'body': '74 64 57', // #4A4039
        'muted': '88 77 71', // #584D47
        'faint': '91 80 73', // #5B5049
        'accent': '27 90 67', // #1B5A43
        'accent-hover': '7 70 49', // #074631
        'accent-fg': '228 223 216', // #E4DFD8
        'accent-soft': '202 218 210', // #CADAD2
        'danger-bg': '239 218 212', // #EFDAD4
        'danger-bg-hover': '246 216 207', // #F6D8CF
        'danger-line': '242 193 178', // #F2C1B2
        'danger-fg': '68 15 0', // #440F00
        'danger-solid': '165 73 43', // #A5492B
        'success-bg': '213 228 220', // #D5E4DC
        'success-bg-hover': '209 227 218', // #D1E3DA
        'success-line': '181 202 192', // #B5CAC0
        'success-fg': '27 90 67', // #1B5A43
        'success-solid': '27 90 67', // #1B5A43
        'warn-bg': '241 223 171', // #F1DFAB
        'warn-line': '216 186 121', // #D8BA79
        'warn-fg': '100 76 9', // #644C09
        'info-bg': '224 216 206', // #E0D8CE
        'info-bg-hover': '232 222 210', // #E8DED2
        'info-line': '223 210 194', // #DFD2C2
        'info-fg': '27 90 67', // #1B5A43
        'cat-violet-bg': '224 216 206', // #E0D8CE
        'cat-violet-line': '223 210 194', // #DFD2C2
        'cat-violet-fg': '88 77 71', // #584D47
        'cat-sky-bg': '224 216 206', // #E0D8CE
        'cat-sky-line': '223 210 194', // #DFD2C2
        'cat-sky-fg': '88 77 71', // #584D47
        'cat-teal-bg': '224 216 206', // #E0D8CE
        'cat-teal-line': '223 210 194', // #DFD2C2
        'cat-teal-fg': '88 77 71', // #584D47
        'cat-orange-bg': '224 216 206', // #E0D8CE
        'cat-orange-line': '223 210 194', // #DFD2C2
        'cat-orange-fg': '88 77 71', // #584D47
        'cat-rose-bg': '224 216 206', // #E0D8CE
        'cat-rose-line': '223 210 194', // #DFD2C2
        'cat-rose-fg': '88 77 71', // #584D47
        'scrim': '57 46 39', // #392E27
      },
      highContrast: {
        'line': '115 103 89', // #736759
        'line-strong': '89 78 64', // #594E40
        'field-line': '89 78 64', // #594E40
        'body': '46 36 30', // #2E241E
        'muted': '58 49 42', // #3A312A
        'faint': '58 49 42', // #3A312A
      },
      shadow: {
        card: '0 1px 2px rgba(57,46,39,.05)',
        raised: '0 2px 4px rgba(57,46,39,.04), 0 10px 26px -10px rgba(57,46,39,.12)',
        pop: '0 8px 12px -4px rgba(57,46,39,.07), 0 18px 36px -12px rgba(57,46,39,.16)',
        inset: 'inset 0 0 0 rgba(0,0,0,0)',
      },
    },
    dark: {
      tokens: {
        'canvas': '26 21 16', // #1A1510
        'surface': '34 29 23', // #221D17
        'raised': '41 36 30', // #29241E
        'sunken': '21 17 11', // #15110B
        'line': '51 45 37', // #332D25
        'line-strong': '77 70 63', // #4D463F
        'field-line': '123 112 98', // #7B7062
        'ink': '210 196 187', // #D2C4BB
        'body': '187 174 166', // #BBAEA6
        'muted': '168 156 148', // #A89C94
        'faint': '155 144 136', // #9B9088
        'accent': '132 163 116', // #84A374
        'accent-hover': '150 182 134', // #96B686
        'accent-fg': '26 21 16', // #1A1510
        'accent-soft': '28 37 24', // #1C2518
        'danger-bg': '46 24 24', // #2E1818
        'danger-bg-hover': '58 33 32', // #3A2120
        'danger-line': '83 43 42', // #532B2A
        'danger-fg': '247 175 171', // #F7AFAB
        'danger-solid': '187 87 87', // #BB5757
        'success-bg': '27 34 23', // #1B2217
        'success-bg-hover': '36 44 31', // #242C1F
        'success-line': '45 54 41', // #2D3629
        'success-fg': '132 163 116', // #84A374
        'success-solid': '109 139 93', // #6D8B5D
        'warn-bg': '42 32 9', // #2A2009
        'warn-line': '75 59 19', // #4B3B13
        'warn-fg': '212 183 118', // #D4B776
        'info-bg': '41 36 30', // #29241E
        'info-bg-hover': '43 37 31', // #2B251F
        'info-line': '51 45 37', // #332D25
        'info-fg': '132 163 116', // #84A374
        'cat-violet-bg': '41 36 30', // #29241E
        'cat-violet-line': '51 45 37', // #332D25
        'cat-violet-fg': '168 156 148', // #A89C94
        'cat-sky-bg': '41 36 30', // #29241E
        'cat-sky-line': '51 45 37', // #332D25
        'cat-sky-fg': '168 156 148', // #A89C94
        'cat-teal-bg': '41 36 30', // #29241E
        'cat-teal-line': '51 45 37', // #332D25
        'cat-teal-fg': '168 156 148', // #A89C94
        'cat-orange-bg': '41 36 30', // #29241E
        'cat-orange-line': '51 45 37', // #332D25
        'cat-orange-fg': '168 156 148', // #A89C94
        'cat-rose-bg': '41 36 30', // #29241E
        'cat-rose-line': '51 45 37', // #332D25
        'cat-rose-fg': '168 156 148', // #A89C94
        'scrim': '0 0 0', // #000000
      },
      highContrast: {
        'line': '123 111 97', // #7B6F61
        'line-strong': '154 141 126', // #9A8D7E
        'field-line': '154 141 126', // #9A8D7E
        'body': '232 219 211', // #E8DBD3
        'muted': '212 200 192', // #D4C8C0
        'faint': '199 187 179', // #C7BBB3
      },
      shadow: {
        card: '0 2px 8px rgba(0,0,0,.35)',
        raised: '0 6px 20px -6px rgba(0,0,0,.5)',
        pop: '0 12px 34px -10px rgba(0,0,0,.6)',
        inset: 'inset 0 0 0 rgba(0,0,0,0)',
      },
    },
  },
} as const

/** Where each derived theme came from, for the credit in Help. */
export const DERIVED_THEME_SOURCES: Record<string, string> = {
  'pebble': 'Jade Pebble Morning',
  'opal': 'Opal Forest Morning',
  'harvest': 'Emerald Harvest Twilight',
}
