import { CONNECTION_COLOURS, PRINT_OVERRIDES, SUN_DOGS } from './themeSunDogs'
import {
  HIGH_CONTRAST_TOKENS,
  THEMES,
  THEME_TOKENS,
  SHADOW_KEYS,
  type ThemeMode,
  type ThemeModeData,
} from './themes'

/**
 * The stylesheet for every theme, written from the data.
 *
 * `frontend/src/themes.css` is this function's output and test/themes.test.ts
 * fails if the two differ, so editing the file by hand is not a way to change a
 * theme. Run `npm run themes:css` after changing shared/themes data.
 *
 * Which block applies, and why the selectors are the way they are:
 *  - The default theme is the base `:root` (light) and `[data-theme='dark']`, so
 *    a page that has not run a script yet is already the default.
 *  - Every other theme is `[data-palette='x'][data-theme='y']`, two attributes,
 *    which out-ranks the base without depending on source order.
 *  - "Higher contrast" adds `[data-contrast='high']` for the default and a third
 *    attribute for the others, so it strengthens whichever theme is active.
 *  - Print is last and carries four attributes, so a dark or a themed page
 *    still prints as the default's light palette on white paper.
 */

const header = `/*
 * Generated by scripts/build-themes-css.ts from shared/themes.ts.
 * Do not edit this file: change the theme data and run \`npm run themes:css\`.
 * test/themes.test.ts fails if this file and the data disagree.
 */
`

function tokenLines(data: ThemeModeData, indent = '  '): string[] {
  const lines = THEME_TOKENS.map((t) => `${indent}--c-${t}: ${data.tokens[t]};`)
  lines.push('')
  for (const k of SHADOW_KEYS) lines.push(`${indent}--shadow-${k}: ${data.shadow[k]};`)
  return lines
}

function block(selector: string, mode: ThemeMode, data: ThemeModeData, extra: string[] = []): string {
  return [`${selector} {`, `  color-scheme: ${mode};`, ...tokenLines(data), ...extra, '}'].join('\n')
}

function highContrastBlock(selector: string, data: ThemeModeData): string | null {
  if (!data.highContrast) return null
  const lines = HIGH_CONTRAST_TOKENS.map((t) => `  --c-${t}: ${data.highContrast![t]};`)
  return [`${selector} {`, ...lines, '}'].join('\n')
}

function connection(mode: ThemeMode): string[] {
  return ['', ...Object.entries(CONNECTION_COLOURS[mode]).map(([k, v]) => `  --c-${k}: ${v};`)]
}

export function generateThemesCss(): string {
  const parts: string[] = [header]

  // The default theme: light is the base, dark the override.
  parts.push(block(':root', 'light', SUN_DOGS.light, connection('light')))
  parts.push(block("[data-theme='dark']", 'dark', SUN_DOGS.dark, connection('dark')))
  parts.push(highContrastBlock("[data-contrast='high']", SUN_DOGS.light)!)
  parts.push(highContrastBlock("[data-theme='dark'][data-contrast='high']", SUN_DOGS.dark)!)

  for (const theme of THEMES) {
    if (theme.id === 'sun-dogs') continue
    parts.push(`/* ${theme.name} */`)
    for (const mode of ['light', 'dark'] as const) {
      const base = `[data-palette='${theme.id}'][data-theme='${mode}']`
      parts.push(block(base, mode, theme.modes[mode]))
      const hc = highContrastBlock(`${base}[data-contrast='high']`, theme.modes[mode])
      if (hc) parts.push(hc)
    }
  }

  // Paper is white: the default's light palette, whatever theme or mode is on screen.
  const print: ThemeModeData = {
    ...SUN_DOGS.light,
    tokens: { ...SUN_DOGS.light.tokens, ...PRINT_OVERRIDES },
  }
  parts.push(
    [
      '@media print {',
      '  :root,',
      '  :root[data-theme],',
      '  :root[data-theme][data-contrast],',
      '  :root[data-palette][data-theme],',
      '  :root[data-palette][data-theme][data-contrast] {',
      '    color-scheme: light;',
      ...tokenLines(print, '    '),
      ...connection('light').map((l) => (l ? `  ${l}` : l)),
      '  }',
      '}',
    ].join('\n'),
  )

  return parts.join('\n\n') + '\n'
}
