import type { GigOpportunity, SyncTarget, PromoDraft } from '../../api'
import type { ReviewItem } from '../../../../shared/reviewQueue'
import { gigMoves, gigStageLabel, type GigMove } from '../../../../shared/gigStage'
import { Button, type ButtonVariant } from '../../components/ui/Button'

/**
 * The moves a gig offers, styled by what they mean: forward is primary,
 * recording something they did is info, ending it is danger.
 */
const GIG_VARIANT: Record<GigMove['tone'], ButtonVariant> = {
  go: 'primary',
  record: 'info',
  no: 'danger',
}

/**
 * The actions for whichever kind of thing is selected.
 *
 * Gig buttons are **generated by `gigMoves`**, which is `nextGigStatuses` in
 * the stage language — never listed by hand.
 * They used to be a fixed four — Will apply, Applied, Pass, Archive — offered
 * whatever the row's status was, and the PATCH route validates against the
 * same pipeline: on a submitted gig every one of them returned a 400, and on
 * an invited one there was no way to record a booking at all. A button the API
 * refuses is worse than a missing button, because it looks like it worked.
 */
export function DecisionBar({
  item,
  onGig,
  onSync,
  onPromo,
  isSaving,
}: {
  item: ReviewItem
  onGig: (body: Partial<GigOpportunity>) => void
  onSync: (body: Partial<SyncTarget>) => void
  onPromo: (body: Partial<PromoDraft>) => void
  isSaving: boolean
}) {
  const buttons: Array<{ label: string; variant: ButtonVariant; title?: string; run: () => void }> = []

  if (item.source.kind === 'gig') {
    for (const move of gigMoves(item.source.row.status, item.source.row.type)) {
      buttons.push({
        label: move.label,
        variant: GIG_VARIANT[move.tone],
        title: move.meaning,
        run: () => onGig({ status: move.to }),
      })
    }
  }

  if (item.source.kind === 'sync') {
    const { status } = item.source.row
    if (status !== 'pitched') {
      buttons.push({ label: 'Mark pitched', variant: 'neutral', run: () => onSync({ status: 'pitched' }) })
    }
    buttons.push({ label: 'Confirmed', variant: 'primary', run: () => onSync({ status: 'confirmed' }) })
    buttons.push({ label: 'Declined', variant: 'danger', run: () => onSync({ status: 'declined' }) })
    buttons.push({ label: 'Archive', variant: 'neutral', run: () => onSync({ status: 'archived' }) })
  }

  if (item.source.kind === 'promo') {
    buttons.push({ label: 'Approve', variant: 'primary', run: () => onPromo({ status: 'approved' }) })
    buttons.push({ label: 'Mark published', variant: 'neutral', run: () => onPromo({ status: 'published' }) })
  }

  // An archived gig has nowhere left to go, and a row of no buttons under a
  // heading reads as a rendering bug. Say why instead.
  if (buttons.length === 0) {
    return (
      <p className="text-xs text-muted">
        Nothing left to decide — {gigStageLabel(item.status).meaning.toLowerCase()}
      </p>
    )
  }

  return (
    <div className="flex flex-wrap gap-2">
      {buttons.map((b) => (
        <Button key={b.label} variant={b.variant} title={b.title} onClick={b.run} disabled={isSaving}>
          {b.label}
        </Button>
      ))}
    </div>
  )
}
